### ISSUE TITLE
`Failed to continue: launch the application failed`

### ISSUE THREAD

**Issue by GamerGirlandCo** [Chaos1323/ASD#3]
`launch.json` contents:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "ASD",
            "request": "launch",
            "name": "Smali Launch",
            "packageName": "com.drakeet.purewriter",
            "mainActivity": "com.drakeet.purewriter.WriterActivity",
            "deviceId": "711KPVH0810063",
            "workDir": "${workspaceFolder}"
        }
    ]
}
```

am i doing something wrong?

**Comment by GamerGirlandCo** [comment]
also changing the `type` to `smali` makes vscode complain that there's no extension installed to debug it.

please? anyone?

**Comment by surendrajat** [comment]
> am i doing something wrong?

Is the device ID correct? You can also try to force close the app before launching the debugger. It happened to me too, but can't reproduce now.

> also changing the type to smali makes vscode complain that there's no extension installed to debug it.

Yeah that was incorrect. You should use `ASD` as per README. I've opened #4  to fix that.

**Comment by GamerGirlandCo** [comment]
> Is the device ID correct? You can also try to force close the app before launching the debugger. It happened to me too, but can't reproduce now

pretty sure it is (see below).

```
PS C:\Users\<redacted>\ApkProjects\Pure Writer Writing Note_v19.109.6_apkpure.com> adb devices -l
List of devices attached
711KPVH0810063         device product:taimen model:Pixel_2_XL device:taimen transport_id:2
```

unless the first value (`711...063`) isn't actually the device id?

**Comment by surendrajat** [comment]
> unless the first value (711...063) isn't actually the device id?

It's device ID, yes. For me, it's usually lowercase, so was wondering lol.

**Comment by Chaos1323** [comment]
run this command in the cmd : "adb -s 711KPVH0810063 shell am start -D -n com.drakeet.purewriter/com.drakeet.purewriter.WriterActivity", then check wether the application start.

**Comment by GamerGirlandCo** [comment]
okay so
i figured it out — the app had a manifest entry that disguises the process name as systemui. getting rid of it and recompiling with `android:debuggable="true"` did the trick :)
